### ISSUE TITLE
roslaunch agn_gazebo static_velodyne.launch

### ISSUE THREAD

**Issue by yxf010** [agn-7/agn_gazebo#2]
~/ros_source/catkin_ws$ roslaunch agn_gazebo static_velodyne.launch
**[static_velodyne.launch] is neither a launch file in package [agn_gazebo] nor is [agn_gazebo] a launch file name**
The traceback for the exception was written to the log file

**Comment by yxf010** [comment]
roslaunch agn_gazebo static_velodyne.launch
**ResourceNotFound: velodyne_description**
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/phe/ros_source/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share

**Comment by agn-7** [comment]
I wrote its answer in the [previous issue](https://github.com/agn-7/agn_gazebo/issues/1).

**Comment by yxf010** [comment]
i had reload you peoject,there is content the file :velodyne_description,but this problem was still exists.

**Comment by agn-7** [comment]
Did you do `catkin_make` after `pull` this repo?

**Comment by yxf010** [comment]
yes,ofcause.

roslaunch agn_gazebo static_velodyne.launch
WARNING: Could not change permissions for folder [/home/phe/.ros/log/4c9489ca-61d3-11e9-900f-3ca9f47fff2c], make sure that the parent folder has correct permissions.
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 749, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 721, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 665, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 257, in _param_tag
    vals = self.opt_attrs(tag, context, ('value', 'textfile', 'binfile', 'command'))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 202, in opt_attrs
    return [self.resolve_args(tag_value(tag,a), context) for a in attrs]
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 370, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 383, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 151, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 197, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
**ResourceNotFound: velodyne_description**
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/phe/ros_source/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share

**Comment by agn-7** [comment]
Apparently, `velodyne_description` not made before `agn_gazebo`, so remove `agn_gazebo` except `velodyne_description`, then do `catkin_make` to make `velodyne_description` package, then recover `agn_gazebo` and do `catkin_make`.

---
`agn_gazebo` has a dependency on `velodyne_description`, so `velodyne_description` must make first.

**Comment by yxf010** [comment]
it do not work




发自我的iPhone

------------------ Original ------------------

**Comment by agn-7** [comment]
What is your error?

Did you remove `agn_gazebo` except `velodyne_description` package? Could you make `velodyne_description` by `catkin_make`? if yes, could you find this package by `roscd velodyne_description`?
